feat: Loading component for initialization and fetching
c6o/ui pull request #36
Opened 2020-09-09 00:38 UTC by Canuckaholic

## Description

Creation of a "loading" component for handling the initial page load and also when a fetch of data is happening and the UI needs to refresh.

Related to https://github.com/c6o/node-monorepo/issues/760

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2020-09-09 19:28 UTC, nsainaney requested changes

2020-09-09 19:44 UTC, Canuckaholic commented on packages/web/src/loaders/loading.ts
>  @customElement('c6o-loading')
we already have `c6o-progress-bar`. How about `c6o-initialization`?

2020-09-14 17:47 UTC, nsainaney requested changes

2020-09-14 17:47 UTC, nsainaney commented on packages/web/src/animations/loading.ts
> +
```suggestion
    @property({ type: Boolean, attribute: 'simple' })
    simpleUI = false

```

2020-09-14 17:47 UTC, nsainaney commented on packages/web/src/store/panel.ts
> +    text = 'Loading...'
```suggestion
    loadingMessage = 'Loading...'
```

2020-09-14 17:47 UTC, nsainaney commented on packages/web/src/store/state.ts
> +    text = 'Loading...'
```suggestion
    loadingMessage = 'Loading...'
```

2020-09-14 17:47 UTC, nsainaney commented on packages/web/src/store/state.ts
> +    barOnly = false
```suggestion
    @property({ type: Boolean, attribute: 'simple' })
    simpleUI = false
```

2020-09-17 03:14 UTC, nsainaney approved these changes

2020-09-17 03:14 UTC, merged